# Generated by Django 5.1.4 on 2025-02-14 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='user',
        ),
        migrations.AddField(
            model_name='request',
            name='ategory',
            field=models.CharField(choices=[('Техническая', 'Техническая'), ('Финансовая', 'Финансовая'), ('Общая', 'Общая')], default='Техническая', max_length=50, verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='request',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='requests/', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='request',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='request',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('Ожидание', 'Ожидание'), ('Решено', 'Решено')], default='Ожидание', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='request',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
    ]
