# Generated by Django 5.1.4 on 2025-02-15 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_request_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='image_after',
            field=models.ImageField(blank=True, null=True, upload_to='reports/after/', verbose_name='Фото после (заполняет админ)'),
        ),
        migrations.AddField(
            model_name='report',
            name='image_before',
            field=models.ImageField(blank=True, null=True, upload_to='reports/before/', verbose_name='Фото до'),
        ),
        migrations.AddField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('pending', 'В ожидании'), ('resolved', 'Решено')], default='pending', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='report',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='report',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='report',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='reports/', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='report',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
    ]
