# Generated by Django 5.1.4 on 2025-02-16 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_request_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('Новая', 'Новая'), ('Решена', 'Решена'), ('Отклонена', 'Отклонена')], default='Новая', max_length=20, verbose_name='Статус'),
        ),
    ]
